### ISSUE TITLE
Transliterating ड ढ

### ISSUE THREAD

**Issue by PhyloStar** [sanskrit-coders/indic_transliteration#15]
https://github.com/sanskrit-coders/indic_transliteration/blob/master/indic_transliteration/sanscript.py#L398

Thanks for the nice package.

The code does not transliterate ड़, ढ़ since they are coded as ड, ढ in Devnagari.

**Comment by vvasuki** [comment]
How do you propose this be solved? (Please see [this sheet](https://docs.google.com/spreadsheets/d/1o2vysXaXfNkFxCO-WD77C4AEbXcAcJmDVgUb-E0mYbg/edit#gid=0).)
xsanscript.py might be a good place to include these non-sanskrit transliterations.

**Comment by vvasuki** [comment]
Transliteration for ड़, ढ़ added for scripts where corresponding characters are clearly specified.
