### ISSUE TITLE
Support for Urdu

### ISSUE THREAD

**Issue by dufferzafar** [sanskrit-coders/indic_transliteration#16]
I tried converting a sentence with Urdu words (`junoon`, `mojiza`) to devanagari script and the output is:

```python
>>> from indic_transliteration import sanscript
>>> from indic_transliteration.sanscript import SchemeMap, SCHEMES, transliterate

>>> data = "Ye mere junoon ka hai mojiza"

>>> print(transliterate(data, sanscript.HK, sanscript.DEVANAGARI))

ए मेरे जुनोओन् क है मोजिश
```

Whereas, for the same sentence, [Google Input Tools' Transliteration](https://www.google.co.in/inputtools/try/) gives:

`ये मेरे जूनून का है मोजिज़ा`

Which is the "right thing".

I know very little about algorithmic transliteration so not sure if this should be added as a different `Scheme` or not, but yeah, having such a support would be amazing!

**Comment by codito** [comment]
Try `ye mere jUnUn kA hai mojijA`

Note the vowels and consonants don't map as-it-is from English to Devanagari. E.g. `आ` is `A` and similar for `U` etc.. Please refer the table in <https://en.wikipedia.org/wiki/Harvard-Kyoto>

**Comment by drdhaval2785** [comment]
@dufferzafar you will have to give some standard romanization scheme for Urdu, if it is to be supported.

**Comment by dufferzafar** [comment]
@drdhaval2785 Can you point me to the code that has similar schemes for other scripts? That'll help me understand it better.

**Comment by drdhaval2785** [comment]
https://github.com/sanskrit-coders/indic_transliteration/blob/master/indic_transliteration/sanscript/schemes/roman.py for code
