### ISSUE TITLE
Hindi and Bengali transliteration contains English characters. 

### ISSUE THREAD

**Issue by mithun-dhali-cookifi** [sanskrit-coders/indic_transliteration#21]
def transliterate_hi(data: str) -> str:
    return sanscript.transliterate(data, sanscript.ITRANS, sanscript.DEVANAGARI)

print(transliterate_hi("Chicken"))
print(transliterate_hi("Egg"))
print(transliterate_hi("Rice"))
print(transliterate_hi("Basmati"))
print(transliterate_hi("Mutton"))

छिcकेन्
Eग्ग्
Rइcए
Bअस्मति
ंउत्तोन्

I am getting the feeling that I am not going something right.

My end goal is to write Chiken in hindi, bengali, kannada for our app.

**Comment by vvasuki** [comment]
Please familiarize yourself with the [ITRANS transliteration scheme](https://en.wikipedia.org/wiki/ITRANS) .

You should transliterate the following strings: chikan, egg, raisam, baasmati, maTTan etc

**Comment by mithun-dhali-cookifi** [comment]
Thanks, got it. 
If i want to convert "Chiken", "Mutton" to hindi, would you have any recommended solution

**Comment by vvasuki** [comment]
No
