### ISSUE TITLE
request for addition of search-friendly transliteration scheme

### ISSUE THREAD

**Issue by drdhaval2785** [sanskrit-coders/indic_transliteration#25]
# Requirement

Usually when an Indian searches for शङ्कराचार्य, in all probabilities he will type 'shankaracharya' or something similar.

He will not write sha~NkarAchArya (itrans), zaGkarAcArya (HK), śaṅkarācārya (IAST) or SaNkarAcArya (SLP1).

When one creates a metadata for maximum landing on the desired entry, we need to have a transliteration scheme which matches the conventions followed by the net users, even if it may be one way transliteration. I needed one such functionality in one of my scripts which needed to put metadata in maximum type of transliteration schemes, so that anyone can land on the page by any transliteration scheme.

# Primitive implementation

A very primitive implementation is at https://github.com/drdhaval2785/ChunilalGandhiVidyabhavan/blob/master/scripts/vernacular.py. Name of transliteration scheme etc can be discussed later on.

@vvasuki and @avinashvarna may be interested, given their discussions on supporting alternate transliteration scheme.

**Comment by vvasuki** [comment]
Implemented with https://github.com/sanskrit-coders/indic_transliteration/commit/4de2346a92433dc4d9548c38be16e9be172cf631 :
`assert sanscript.SCHEMES[sanscript.OPTITRANS].to_lay_indian("kRShNa") == "krishna"`
