### ISSUE TITLE
Gurmukhi errors

### ISSUE THREAD

**Issue by drdhaval2785** [sanskrit-coders/indic_transliteration#27]
1. ਉਪਦੇਸ਼ੇఽਜਨਨੁਨਾਸਿਕ ਇਤ੍

Here ఽ stands for Telugu avagraha as far as google says.
Gurmukhi avagraha is the same as Devanagari.

**Comment by vvasuki** [comment]
Fixed the avagraha, but did not update the library (leaving it for resolution of https://github.com/sanskrit-coders/indic_transliteration/issues/28 ).
