### ISSUE TITLE
Gurmukhi issue for version > 1.7.4

### ISSUE THREAD

**Issue by drdhaval2785** [sanskrit-coders/indic_transliteration#28]
I do not read or write Gurmukhi.
But only one of my tests which converted from SLP1 to Gurmukhi failed.
So reporting the issue here.

# Problem statement

1. As long as the indic_transliteration version was 1.7.4 , there was no issue. Python 2.7, 3.4, 3.5, 3.7 and pypy used to pass build. See https://travis-ci.org/drdhaval2785/python-prakriya/builds/438689540
2. When the version was bumped to 1.7.5 on 12.10.2018, even my pyup update PRs started to fail. There is not a single line of code change on my side except the PR of version updation of dependencies by pyup. See https://travis-ci.org/drdhaval2785/python-prakriya/builds/438689540. Only substantial change was the release of 1.7.5 of indic_transliteration. I used to require indic_transliteration>=1.6.2.
3. I understand that python2 support was withdrawn in between. But the unique thing was that the test used to fail in python3 only. python2 used to pass as usual. See https://travis-ci.org/drdhaval2785/python-prakriya/builds/441698231.
4. Then I changed the requirements to indic_transliteration==1.7.4, and the build started to pass without any hassle. See https://travis-ci.org/drdhaval2785/python-prakriya/builds/468641357

# Potential error identification

1. My test suite had generated step by step derivation of 'bhavati' in all possible transliteration schemes by earlier version of indic_transliteration package. 
2. In changing from 1.7.4 to 1.7.5, there occurred something abnormal which broke the test for Gurmukhi. All others passed as usual.

# Differences
https://jsoneditoronline.org/?id=4ab0f7db34534b62aeca179ce3df5e3a gives the differences in the large dict of step by step derivation.

1. Avagraha issue - See https://github.com/sanskrit-coders/indic_transliteration/issues/27
2. Incosistent `\ufffd`. Sometimes the earlier version used to emit three consecutive entries. Sometimes the present version emits three consecutive `\ufffd`.

**Comment by vvasuki** [comment]
namaste dhaval,

could you add test cases which fail to tests/data/transliterationTests.json , and if possible fix the issue and then tell me to update the library?

**Comment by vvasuki** [comment]
(sent you an invitation so that you may directly contribute to the repo)

**Comment by drdhaval2785** [comment]
It is very difficult for me to do, because I do not understand Gurmukhi.
