### ISSUE TITLE
Keep a changelog

### ISSUE THREAD

**Issue by drdhaval2785** [sanskrit-coders/indic_transliteration#29]
Many utilities like pyup etc complain regarding non availability of changelog. Keep a changelog for versiin change.

**Comment by drdhaval2785** [comment]
![screenshot_20181217-201228_samsung internet](https://user-images.githubusercontent.com/5755132/50094140-76703500-0238-11e9-9d30-0aa1c05683eb.jpg)

**Comment by vvasuki** [comment]
This would be too much of a hazzle - dropping this.
