### ISSUE TITLE
Error with Devanagari

### ISSUE THREAD

**Issue by kmadathil** [sanskrit-coders/indic_transliteration#3]
>>> sanscript.transliterate("गच्छ",sanscript.DEVANAGARI, sanscript.HK)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/karthick/anaconda2/lib/python2.7/site-packages/indic_transliteration/sanscript.py", line 347, in transliterate
    return func(data, scheme_map, **options)
  File "/home/karthick/anaconda2/lib/python2.7/site-packages/indic_transliteration/sanscript.py", line 311, in _brahmic
    return ''.join(buf)
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe0 in position 0: ordinal not in range(128)

**Comment by vvasuki** [comment]
`sanscript.transliterate(u"गच्छ",sanscript.DEVANAGARI, sanscript.HK)` :-) 
Added that example to README.

**Comment by kmadathil** [comment]
Thanks! Might want to add a line in the README that non-literals need to be encoded before passing them to achieve the same effect.
```
  # thing is of type str
  thing_u = unicode(thing,'utf-8')  
  thing_t  = sanscript.transliterate(thing_u, sanscript.DEVANAGARI,sanscript.HK)
```
I have used a typecheck in my class wrapper to check for a non-unicode type and encode it if necessary to get around this.

**Comment by vvasuki** [comment]
I could just link to [this note on good practices for dealing with python unicode string literals](https://sites.google.com/site/sanskritcode/tutorials/python-unicode) I suppose..
