### ISSUE TITLE
Error after installation

### ISSUE THREAD

**Issue by vivekbetu** [sanskrit-coders/indic_transliteration#30]
After following up the steps I successfully installed Python on my CentOS 6.10 Server. 
Python version is Python 2.6
indic-transliteration version  1.7.8 

Error!
![error](https://user-images.githubusercontent.com/4180536/51021724-5bc77c80-15a8-11e9-9d97-db4cd393e81d.JPG)

translate.py:
`from indic_transliteration import sanscript
from indic_transliteration.sanscript import SchemeMap, SCHEMES, transliterate

data="Hello World!"
print(transliterate(data, sanscript.ITRANS, sanscript.DEVANAGARI))`

**Comment by drdhaval2785** [comment]
https://github.com/sanskrit-coders/indic_transliteration/commit/b58ee9fb1276a86f6d4c6bca6f27090193cc8619 dropped support for python2.

**Comment by drdhaval2785** [comment]
`pip install indic_transliteration=1.7.4` used to work for me for python 2.7. Should also work for python 2.6 also in my opinion.

**Comment by vivekbetu** [comment]
I have installed it using following command pip install indic-transliteration==1.7.4
But it's still not working I guess I can't use it for Python 2.6 :(

**Comment by drdhaval2785** [comment]
https://www.python.org/dev/peps/pep-0274/ says that dict comprehension was introduced in 2.7 only. So 2.6 would not be supported.
I looked at the error. It seems that it is sheerly because dict comprehension was not supported before 2.7.

```python
inv_map = {}
for k, v in self.consonants.items():
    inv_map[v] = k
```

Try replacing the line 163 with this snippet. May work.
