### ISSUE TITLE
WX Notation Corrections

### ISSUE THREAD

**Issue by hrishikeshrt** [sanskrit-coders/indic_transliteration#31]
https://en.wikipedia.org/wiki/WX_notation

According to the above, 
Z is used for avagraha (ऽ)
z is for anunasika (third character in yogavaahas, e.g. az = अँ)

roZsupi should transliterate to 'रोऽसुपि'
kasmizSciw should transliterate to 'कस्मिँश्चित्'

while currently they transliterate as 'रोZसुपि' and 'कस्मिzश्चित्' respectively.

**Comment by vvasuki** [comment]
Fixed
