### ISSUE TITLE
Issues with Anushwaars and Talavya श  Devanagri

### ISSUE THREAD

**Issue by pynyah** [sanskrit-coders/indic_transliteration#32]
Hi,

Thanks for creating this library. has been helpful. However, I am facing issues when it comes to Anushwaars & "श" . I am trying to transliterate from Hindi to english. ANushwaars is being read "M" instead of "N" and ""श" is being read as "Z" instead of "Sh". How can I fix this?

Thanks

**Comment by vvasuki** [comment]
Please write down the line of code used along with the expected output. (Perhaps you're using the library wrong.)

**Comment by sirius0503** [comment]
Hi @vvasuki : I am also facing the same problem, I am unable to understand how to add the fix for `lazy_anusvaara's`. 

My code is below:

I saw the source code [fix_lazy_anusvaaras](https://sanskrit-coders.github.io/indic_transliteration/build/html/_modules/indic_transliteration/sanscript/schemes.html#Scheme.fix_lazy_anusvaara), but cannot understand the `params` for the class and the method fix_lazy_anusvaaras,

```
# I have a csv file named transhindi, which with the hindi words in the `word` column, I'm trying to create a new column named new_itrans.
import pandas as pd
from indic_transliteration import sanscript
from indic_transliteration.sanscript import SchemeMap, SCHEMES, transliterate
from indic_transliteration.sanscript.schemes import Scheme

assert sanscript.SCHEMES[sanscript.ITRANS].fix_lazy_anusvaara("shaMkara") == "sha~Nkara"
assert sanscript.SCHEMES[sanscript.ITRANS].fix_lazy_anusvaara("saMchara") == "sa~nchara"
assert sanscript.SCHEMES[sanscript.ITRANS].fix_lazy_anusvaara("saMvara") == "sav.Nvara"
assert sanscript.SCHEMES[sanscript.ITRANS].fix_lazy_anusvaara("saMyukta") == "say.Nyukta"
assert sanscript.SCHEMES[sanscript.ITRANS].fix_lazy_anusvaara("saMlagna") == "sal.Nlagna"


df = pd.read_csv('transhindi.csv')
#print(df.head())

print(df.columns)

df['new_itrans'] = df['word'].apply(lambda x : transliterate(x , sanscript.DEVANAGARI, sanscript.ITRANS))

print(df.head(60))

```

Also, I read in [this research paper](https://arxiv.org/pdf/1809.07807.pdf), that transliterating is the process of transducing
names from one writing system to another (e.g.,
ओबामा in Devanagari to Obama in Latin script)
**while preserving their pronunciation**. 

Is it correct to say that , and also do methods such as Harvard-Kyoto, ITRANS, VELTHUIS, IAST, do preserve the pronunciation or are they simply a mapping system, as I surmise.

**Comment by vvasuki** [comment]
namate, 

Same suggestion to you: Please write down the line of code used along with the expected output. (Perhaps you're using the library wrong.)

> Is it correct to say that , and also do methods such as Harvard-Kyoto, ITRANS, VELTHUIS, IAST, do preserve the pronunciation or are they simply a mapping system, as I surmise.

They preserve pronunciation as well.

**Comment by sirius0503** [comment]
@vvasuki : If I use ITRANS, I get capitalized letters like 'A' , etc. but I don't want that, so when I use `VELTHUIS`, I get the following output:
```

Index(['word', 'wordeng'], dtype='object')
           word         wordeng             new_words
0           अजय            Ajay                 ajaya
1      रावसाहेब        Raosaheb          raavasaaheba
2         राठोड          rathod            raa.tho.da
3           शहर          sheher               "sahara
4           गाव            Gaon                 gaava
5   जगसोंडतांडा  jagasondatanda  jagaso.m.dataa.m.daa
6         तहसील          tehsil             tahasiila
7       पाथर्डी        pathardi           paathar.dii
8         पोलीस          Police               poliisa
9        स्टेशन         Station             s.te"sana
10       जिल्हा           Zilha                jilhaa
11      अहमदनगर      Ahemdnagar         ahamadanagara
12        राज्य           Rajya                raajya
13   महाराष्ट्र     Maharashtra        mahaaraa.s.tra
14         भारत          Bharat              bhaarata
15        संदिप          sandip              sa.mdipa
16         शंकर         Shankar             "sa.mkara
17         सानप           sanap               saanapa
18           1.              1.                    1.
19      मिनाबाई         minabai            minaabaaii
20       शिवाजी         Shivaji             "sivaajii
21     वाघापुरे       vaghapure           vaaghaapure
22     चाळीसगाव      chalisagav         caaLiisagaava
23      नांदगाव        nandagav          naa.mdagaava
24     नांदगांव       nandaganv        naa.mdagaa.mva
25        नाशिक          Nashik              naa"sika
26      ग्रामीण          gramin            graamii.na
27       दिगंबर        Digambar            diga.mbara
28       कुशाबा         Kushaba             ku"saabaa
29        नरोटे          narote               naro.te
30        महुरी          mahuri               mahurii
31      बाळकष्ण       balakashn          baaLaka.s.na
32       अर्जुन           Arjun                arjuna
33        पालवे          palave               paalave
34  कोल्हुबाईचे     kolhubaiche          kolhubaaiice
35      कोल्हार          kolhar              kolhaara
36       अनोळखी        anolakhi             anoLakhii
37        किशोर          Kishor               ki"sora
38       गंगाधर       Gangadhar          ga.mgaadhara
39        बोरसे          borase                borase
40     निवडुंगे       nivadunge           niva.du.mge
41        उध्दव          udhdav               udhdava
42     कोंडीराम        kondiram         ko.m.diiraama
43         मरकड         marakad             maraka.da
44          भरत          bharat               bharata
45      बाबुराव         Baburao            baaburaava
46         जाधव          Jadhav              jaadhava
47         पोका            poka                 pokaa
48         अतुल            Atul                 atula
49         अशोक           Ashok                a"soka
50        शेळके         shelake               "seLake
51           पो              po                    po
52         स्टे            Stay                  s.te
53     भाऊसाहेब       bhausaheb         bhaauusaaheba
54      मुरलीधर       Murlidhar          muraliidhara
55         मोहज           mohaj                mohaja
56           खु             khu                   khu
57       मंडमबी       mandamabi          ma.m.damabii
58      जाफरभाई      jafarabhai        jaapharabhaaii
59          शेख          Shaikh                "sekha
```


This is from using `sanscript.VELTHUIS`, As you can see , I want the output to be like the second column of `word_eng` and in cases such as 13, I am getting two `a`s , for 3) I get `shahara` , whilst I want `sheher`, for 16) Shankar, I gete `sa.mkar, for 4)Gaon I get `Gaava`, Similarly for 1) Raavasaaheba.

**Comment by vvasuki** [comment]
namate - Looks like you would get most (but not all) of what you want by using sanscript.OPTITRANS, then converting to lowercase, removing double vowels, removing the final a. Most of this library is meant for sanskrit-based transliteration while preserving the pronunciation - but, feel free to contribute an function to post process the output of the sanskrit-based functions in order to support regional languages.

**Comment by shreevatsa** [comment]
@sirius0503 Also, it's possible you misunderstand the purpose of this library: it is to provide transliteration, not transcription (Romanization). The goal of transliteration is to be a lossless representation of the text from one script in another, such that the pronunciation is preserved (assuming the reader knows how to read the target script, i.e. knows how to read IAST or ITRANS or Velthuis or whatever). The goal of transcription/Romanization is to simply approximate into Roman script in a sloppy way using ad-hoc and inconsistent conventions of English spelling and regional practice thereof (relying on the reader to apply judgment and semantic context to recover the original text, and not bothering too much if this fails).

To illustrate: in your examples, you say you want `राठोड` to result in `rathod`. If you don't have a way of marking long vowels versus short vowels, and retroflex consonants (मूर्धन्य, ट-वर्ग) from dental (दन्त्य, त-वर्ग), how would you distinguish between the results of transliterating राठोड राथोड राठोद राथोद रठोड रथोड रठोद रथोद as it appears all 8 of them would result in `rathod`? (Another example: the list says you want `भारत` to result in `Bharat` and `भरत` to result in `bharat` — this is not transliteration that preserves pronunciation, this is just “write the word in English and hope that the reader knows what you mean”. Which is a perfectly fine thing to want, but not the goal of transliteration proper even if you can use this library somehow to obtain it.)
