### ISSUE TITLE
fix_lazy_anusvaara issue with 1.9.5

### ISSUE THREAD

**Issue by kmadathil** [sanskrit-coders/indic_transliteration#39]
Unexpected behavior seen in package version 1.9.5, not seen in prior versions

```
sanscript.SCHEMES[sanscript.SLP1].fix_lazy_anusvaara("aham")
'अहम्'
```
Previous version output
```
>>> sanscript.SCHEMES[sanscript.SLP1].fix_lazy_anusvaara("aham")
'aham'
```
This breaks sanskrit_parser. Is there a change of definition for this method?

**Comment by vvasuki** [comment]
That was a regression bug. Fixed and tested with https://github.com/sanskrit-coders/indic_transliteration/commit/0a43c6e0dc852bf13d80d7cd7a94fe9050b761c7 . Bumped up version to `1.9.7`. Thanks for reporting.
