### ISSUE TITLE
Support for Tamil alternate consonants

### ISSUE THREAD

**Issue by karthikraman** [sanskrit-coders/indic_transliteration#4]
How does one encode / transliterate Tamil alternate consonants, e.g. ற, ன (r2, n2 perhaps?)

**Comment by vvasuki** [comment]
Transliterate to which (presumably extended sanskrit) roman schema? If you seek some cousin of IAST, https://www.loc.gov/catdir/cpso/romanization/tamil.pdf is a possibility : 
![image](https://user-images.githubusercontent.com/2664797/29739173-59a8fdfa-89ec-11e7-8908-1ea470da1c00.png)

**Comment by karthikraman** [comment]
Perhaps, ऱ/r̂ and ऩ/n̂/n(!) - it's a bit peculiar, esp. the ऩ, as even the pronunciation is no different!

**Comment by karthikraman** [comment]
I think the best solution is to create `xsanscript.py` with support for extended characters, similar to https://github.com/karthikraman/indic_transliteration/commit/bc6db58fee8488e20a97d36738605ca3f2c24568

**Comment by vvasuki** [comment]
मित्र, अधिकृतोऽसि तथा कर्तुम् अधुना।

**Comment by vvasuki** [comment]
तथा च यथोचितम् जातितत्त्व(=inheritence)-प्रयोगं कुरु

**Comment by karthikraman** [comment]
Quick fix via `xsanscript.py` https://github.com/sanskrit-coders/indic_transliteration/commit/c78382e0dbf2255b2feefcd68da1eb0c061cbca1

**Comment by vvasuki** [comment]
साधु, कार्त्तिक। जातितत्त्व(=inheritence)-प्रयोगं कुरुष्व - नाम, (mostly) only code in that file should be that which is changed between the two files.

**Comment by Shreeshrii** [comment]
> e.g. ற, ன (r2, n2 perhaps?)

IAST, ISO - e.g. ṟa, ṉa

ITRANS - e.g. Ra, ^na

Devanagari - e.g. ऱ, ऩ

Please see 

https://en.wikipedia.org/wiki/National_Library_at_Kolkata_romanisation

http://www.virtualvinodh.com/wp/character-matrix/
