### ISSUE TITLE
Is this available as a CLI?

### ISSUE THREAD

**Issue by vipranarayan14** [sanskrit-coders/indic_transliteration#58]
I have to often transliterate files. A CLI version of your tool (which can be run from the terminal) will be very useful instead of having to write python code every time.

Is there one already?

If not, I can help develop one.

**Comment by vipranarayan14** [comment]
Okay. Will update my progress here.

**Comment by vipranarayan14** [comment]
Done. ✨

https://github.com/vipranarayan14/sanscript-cli

I like the name `sanscript`. We can change it if there is some issue.

Kindly share your feedback or any other suggestions.

**Comment by vvasuki** [comment]
Why don't you make it a package in this repo (that's what I was anticipating in some pull request)?

 Makes maintenance and "keeping in sync" simpler.

**Comment by vipranarayan14** [comment]
Sure. That way this repo/package can be used both as a library and as a cli.

I will make changes accordingly and will update.

PS: I usually have separate repos for different interfaces of a library to avoid messing its dependencies. That's why created a seperate repo.

**Comment by vipranarayan14** [comment]
Thank you. Hope it'll be useful for others.
