### ISSUE TITLE
Can't Transliterate Words Like (valuecart, autonics)

### ISSUE THREAD

**Issue by mukeshbadgujar** [sanskrit-coders/indic_transliteration#60]
As i Understand the problem, i think it cant be well recognize the char 'c', so the simple solution is that if it is not transliterate the word then just replace char 'c' with char 'k' so it will transliterate easily. Just Try!

eg. autonics >> 'औतोनिcस्'
     Here the 'c' is problem so just replce 'c' with 'k'  we get >> औतोनिक्स्

print(transliterate('autonics', sanscript.ITRANS, sanscript.DEVANAGARI))
print(transliterate('autoniks', sanscript.ITRANS, sanscript.DEVANAGARI))

**Comment by drdhaval2785** [comment]
Type autoniks and you will get what you want.

**Comment by vvasuki** [comment]
Doing this c -> k replacement in the code will upset the expectations of some users (who might want to distinguish, for example, non-ITRANS from ITRANS text; or use c to represent च). So, if such is to be included, it should be in a separate function. like: SCHEMES[sanscript.ITRANS].pre_replacements_for_english(). Feel free to contribute such a function.

**Comment by mukeshbadgujar** [comment]
> pre_replacements_for_english

yes, Sure .. Will Do that...

There are some other chrs like >>  'z' , 'j' , 'g' sometimes we need to use them in marathi words 
मी जिंकलो >> here sometimes we use 'j' or 'g' depends on word. (this is just for an eg.)

and for that, i think this function is needed.

Thanks For Reply @vvasuki

**Comment by vvasuki** [comment]
> > pre_replacements_for_english
> 
> yes, Sure .. Will Do that...
> 
> There are some other chrs like >> 'z' , 'j' , 'g' sometimes we need to use them in marathi words
> मी जिंकलो >> here sometimes we use 'j' or 'g' depends on word. (this is just for an eg.)
> 
> and for that, i think this function is needed.
> 
> Thanks For Reply @vvasuki

No - constrain yourself to english as far as this function is concerned. Contribute a separate function for marAThi if you like. Look forward to your pull request (closing this).
