### ISSUE TITLE
Words with Chandra bindu (Moon-Dot) are not correctly Transliterate

### ISSUE THREAD

**Issue by mukeshbadgujar** [sanskrit-coders/indic_transliteration#64]
Please Se Below Words:
English:
AUM	 aaNkh
 ttaaNg	 maaN
 paaNc	 aaNsuu
 caaNd	 kaaNc
 muNh	 gaaNtth
 suuNdd	 gaaNv
 paaNv	 chaaNv
 jaaNc	 khaaN
 vhaaN	 yhaaN
 saaNp	 jhaaN
 thaaN	 aaNgn

Hindi:
ॐ	 आँख
 टाँग	 माँ
 पाँच	 आँसू
 चाँद	 काँच
 मुँह	 गाँठ
 सूँड	 गाँव
 पाँव	 छाँव
 जाँच	 कहाँ
 वहाँ	 यहाँ
 साँप	 जहाँ
 तहाँ	 आँगन

If translityerate 

आण्ख् <= aaNkh (Expected: आँख)
माण् <= maaN (Expected: माँ)
आण्सू <= aaNsuu (Expected: आँसू)

If Any Solution Available Please Tell.

**Comment by vvasuki** [comment]
.N should be used. Compare https://github.com/sanskrit-coders/indic_transliteration/blob/7ee621bff40486056d05c0ec25474b8a66ee65a7/indic_transliteration/sanscript/schemes/brahmic/northern.py#L10 and https://github.com/sanskrit-coders/indic_transliteration/blob/7ee621bff40486056d05c0ec25474b8a66ee65a7/indic_transliteration/sanscript/schemes/roman.py#L87

So: `aa.Nkh`

**Comment by mukeshbadgujar** [comment]
Thank You Sooo Much. You are Too Good
