### ISSUE TITLE
Remove dependency on regex module

### ISSUE THREAD

**Issue by drdhaval2785** [sanskrit-coders/indic_transliteration#9]
Today I tried to upgrade my `prakriya` package to add functionality to v0.0.6.
 It uses this package as dependency which in turn uses `regex` module as dependency. 
When I tried to upgrade on my linux server which hosts the API, I got an error that the bdist_wheel build for regex module was Killed and I could not install indic_transliteration and also could not upgrade prakriya package.

The behaviour of regex seems to be unstable. There is one more error regarding failing tox.

I checked the code. There is only one function in sanscript.py which uses this. Can we avoid regex module and use native `re`?

**Comment by drdhaval2785** [comment]
Or nay be specify the regex to a version which is stably built across platforms?

**Comment by vvasuki** [comment]
@drdhaval2785 - यतो भवान् एव दोषं साक्षाद् उत्पादयितुं शक्नोति, तत्परिहारो ऽपि प्रायेण भवदधीनः।

https://travis-ci.org/sanskrit-coders/indic_transliteration इत्यत्र तु सर्वं सम्यगस्तीति दर्शयति ।

**Comment by drdhaval2785** [comment]
Seems non-reproducible issue.
Installed correctly this time.
Closing this. Will reopen if I get any other error.

**Comment by drdhaval2785** [comment]
Just got a new error message on my windows machine.
```
$ pypy -m pip install -U prakriya
Collecting prakriya
  Using cached prakriya-0.0.7-py2.py3-none-any.whl
Requirement already up-to-date: Click>=6.0 in c:\pypy2-v5.10.0-win32\pypy2-v5.10.0-win32\site-packages (from prakriya)
Requirement already up-to-date: requests in c:\pypy2-v5.10.0-win32\pypy2-v5.10.0-win32\site-packages (from prakriya)
Collecting indic-transliteration (from prakriya)
  Using cached indic_transliteration-1.6.2-py2.py3-none-any.whl
Requirement already up-to-date: certifi>=2017.4.17 in c:\pypy2-v5.10.0-win32\pypy2-v5.10.0-win32\site-packages (from requests->prakriya)
Requirement already up-to-date: chardet<3.1.0,>=3.0.2 in c:\pypy2-v5.10.0-win32\pypy2-v5.10.0-win32\site-packages (from requests->prakriya)
Requirement already up-to-date: idna<2.7,>=2.5 in c:\pypy2-v5.10.0-win32\pypy2-v5.10.0-win32\site-packages (from requests->prakriya)
Requirement already up-to-date: urllib3<1.23,>=1.21.1 in c:\pypy2-v5.10.0-win32\pypy2-v5.10.0-win32\site-packages (from requests->prakriya)
Requirement already up-to-date: backports.functools-lru-cache in c:\pypy2-v5.10.0-win32\pypy2-v5.10.0-win32\site-packages (from indic-transliteration->prakriya)
Collecting regex (from indic-transliteration->prakriya)
  Using cached regex-2018.01.10.tar.gz
Installing collected packages: regex, indic-transliteration, prakriya
  Running setup.py install for regex ... error
    Complete output from command C:\pypy2-v5.10.0-win32\pypy2-v5.10.0-win32\pypy.exe -u -c "import setuptools, tokenize;__file__='c:\\users\\dellus~1\\appdata\\local\\temp\\pip-build-le1rhv\\regex\\setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record c:\users\dellus~1\appdata\local\temp\pip-73f5fv-record\install-record.txt --single-version-externally-managed --compile:
    C:\pypy2-v5.10.0-win32\pypy2-v5.10.0-win32\site-packages\setuptools\dist.py:331: UserWarning: Normalizing '2018.01.10' to '2018.1.10'
      normalized_version,
    running install
    running build
    running build_py
    creating build
    creating build\lib.win32-2.7
    copying regex_2\regex.py -> build\lib.win32-2.7
    copying regex_2\_regex_core.py -> build\lib.win32-2.7
    copying regex_2\test_regex.py -> build\lib.win32-2.7
    running build_ext
    building '_regex' extension
    creating build\temp.win32-2.7
    creating build\temp.win32-2.7\Release
    creating build\temp.win32-2.7\Release\regex_2
    C:\Users\dell user\AppData\Local\Programs\Common\Microsoft\Visual C++ for Python\9.0\VC\Bin\cl.exe /c /nologo /Ox /MD /W3 /GS- /DNDEBUG -IC:\pypy2-v5.10.0-win32\pypy2-v5.10.0-win32\include /Tcregex_2\_regex.c /Fobuild\temp.win32-2.7\Release\regex_2\_regex.obj
    _regex.c
    regex_2\_regex.c(9293) : fatal error C1189: #error :  "Needs to be a wide build."
    error: command 'C:\\Users\\dell user\\AppData\\Local\\Programs\\Common\\Microsoft\\Visual C++ for Python\\9.0\\VC\\Bin\\cl.exe' failed with exit status 2

    ----------------------------------------
Command "C:\pypy2-v5.10.0-win32\pypy2-v5.10.0-win32\pypy.exe -u -c "import setuptools, tokenize;__file__='c:\\users\\dellus~1\\appdata\\local\\temp\\pip-build-le1rhv\\regex\\setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record c:\users\dellus~1\appdata\local\temp\pip-73f5fv-record\install-record.txt --single-version-externally-managed --compile" failed with error code 1 in c:\users\dellus~1\appdata\local\temp\pip-build-le1rhv\regex\
```

**Comment by shreevatsa** [comment]
Looking at the usage of `regex` in this code, it seems rather unnecessary to have that dependency; it would make sense to replace it with the standard library `re` as @drdhaval2785 suggested.

**Comment by shreevatsa** [comment]
`re` is part of the Python standard library (see [Python 2 docs](https://docs.python.org/2/library/re.html) or [Python 3 docs](https://docs.python.org/3/library/re.html))

`regex` is a third-party (i.e. someone wrote it other than the Python maintainers) package, which means it needs to be included as an additional dependency, which seems to be failing here. [It](https://pypi.python.org/pypi/regex/) seems to have some additional features, but it's not clear whether any of those features are needed…

BTW the actual error message quoted above, ending with “Needs to be a wide build” may also be a sign of something concerning or at least sub-optimal: a “narrow build” of Python means that certain large Unicode characters (outside the Basic Multilingual Plane, so mainly CJK characters and emoji) may not be treated as single characters. As long as it doesn't cause a problem it may be ok.

**Comment by vvasuki** [comment]
Hmm. 

`key = re.sub("\\P{IsDevanagari}", "", key)` does not seem to work in contrast with `key = regex.sub("\\P{IsDevanagari}", "", key)`. That would need more than a simple substitution.

**Comment by vvasuki** [comment]
Added the below comment:

# Not using the more standard library re here : We need to support `key = re.sub("\\P{IsDevanagari}", "", key)`.
